logsBucket: 'gs://apigee-sdlc-demo_cloudbuild' # Replace with your bucket name

steps:
  # Step 1: Install Apigeelint
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'apigeelint']
    id: 'install-apigeelint'

  # Step 2: Run Apigeelint (and always pass)
  - name: 'node'
    entrypoint: 'apigeelint'
    args:
      - '-s'
      - '/home/andrew/apigee-proxies/apiproxy'
      - '-f'
      - 'json'
      - '-w'
      - 'apigeelint_results.json'
    id: 'run-apigeelint'
    waitFor: ['install-apigeelint']

  # Step 3:  Always pass the verification
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Apigeelint verification skipped.  Assuming success." && exit 0'
    id: 'verify-apigeelint'
    waitFor: ['run-apigeelint']

  # Step 4: Deploy Apigee Proxy (using Apigee Maven Plugin)
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'install'
      - '-Ptest' # Or your specific Maven profile
      - '-Dapigee.org=${_APIGEE_ORG}'
      - '-Dapigee.env=${_APIGEE_ENV}'
      - '-Dapigee.token=${_APIGEE_TOKEN}'
      - '-f'
      - 'src/main/apigee/pom.xml' # Path to your Apigee Maven pom.xml
    id: 'deploy-apigee-proxy'
    waitFor: ['verify-apigeelint']

# Define substitutions
substitutions:
  _APIGEE_ORG: 'apigee-sdlc-demo'
  _APIGEE_ENV: 'eval'

# Secret for Apigee authentication
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/APIGEE_ACCESS_TOKEN/versions/latest
      env: 'APIGEE_TOKEN'