# cloudbuild.yaml
logsBucket: 'gs://apigee-sdlc-demo_cloudbuild'

steps:
  # Step 1: Install Node.js and npm (using a specific Node.js version)
  - name: 'node'  # Use a specific Node.js version (20 or higher)
    entrypoint: 'npm'
    args: ['install', '-g', 'npm@latest']  # Optional: Ensure latest npm (might not be necessary)
    env:
      - 'NPM_CONFIG_UPDATE_NOTIFIER=false' # Suppress npm update messages

  # Step 2: Install apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: 'npm'
    args: ['install', '-g', 'apigeelint']

 # Step 2.5: Inspect the installation location (temporary)
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -l /usr/local/bin /usr/local/lib/node_modules/.bin'  # Check common locations
  
  # Step 3: Run apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: '/usr/local/bin/apigeelint'  # Use the standard global install location
    args:
      - '-s'
      - '/home/andrew/apigee-proxies/apiproxy'
      - '-f'
      - 'table.js'