# cloudbuild.yaml
logsBucket: 'gs://apigee-sdlc-demo_cloudbuild'

steps:
  # Step 1: Install Node.js and npm (if not already part of your base image)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'npm@latest'] # Ensure latest npm version
    env:
      - 'NPM_CONFIG_UPDATE_NOTIFIER=false' # Suppress npm update messages

  # Step 2: Install apigeelint
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'apigeelint']

  # Step 3: Run apigeelint
  # Replace 'path/to/your/apiproxy' with the actual path to your API proxy bundle
  # within your repository.
  # Add other apigeelint options as needed (e.g., -f for format, -e for exclude)
  - name: 'node' # Node.js is required to run apigeelint
    entrypoint: 'apigeelint'
    args:
      - '-s'
      - '/home/andrew/apigee-proxies/apiproxy' # Path to your API proxy bundle
      - '-f'
      - 'table.js' # Example format, you can use 'json.js', 'csv.js', etc.
      # You can add more apigeelint flags here, e.g.:
      # - '-x' # To specify external plugins
      # - '-e' # To exclude specific rules (e.g., -e PO001)

# Optional: You can include build artifacts or other steps after linting
# artifacts:
#   objects:
#     location: 'gs://your-artifact-bucket'
#     paths:
#       - 'apigeelint_report.txt' # If you output the report to a file