# cloudbuild.yaml
logsBucket: 'gs://apigee-sdlc-demo_cloudbuild'

steps:
  # Step 0: Clone the repository (this step is automatically added by Cloud Build if a repository trigger is used)
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--branch=master', 'https://github.com/afgates-google/apigee-proxy.git', 'apigee-proxies']  # Replace with your branch and repository URL
    id: 'clone-repo'

  # Step 1: Install Node.js and npm (using a specific Node.js version)
  - name: 'node'  # Use a specific Node.js version (20 or higher)
    entrypoint: 'npm'
    args: ['install', '-g', 'npm@latest']  # Optional: Ensure latest npm (might not be necessary)
    env:
      - 'NPM_CONFIG_UPDATE_NOTIFIER=false' # Suppress npm update messages

  # Step 2: Install apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: 'npm'
    args: ['install', '-g', 'apigeelint']

  # --- DIAGNOSTIC STEPS ---
  # (Keep your diagnostic steps for now, they might still be useful)

  # Step 3: Run apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: 'npx'  # Use npx to find and execute apigeelint
    args:
      - 'apigeelint'
      - '-s'
      - 'apigee-proxies/apiproxy'  # Update the path to reflect the cloned repository
      - '-f'
      - 'table.js'
