# cloudbuild.yaml
logsBucket: 'gs://apigee-sdlc-demo_cloudbuild'

steps:
  # Step 1: Install Node.js and npm (using a specific Node.js version)
  - name: 'node'  # Use a specific Node.js version (20 or higher)
    entrypoint: 'npm'
    args: ['install', '-g', 'npm@latest']  # Optional: Ensure latest npm (might not be necessary)
    env:
      - 'NPM_CONFIG_UPDATE_NOTIFIER=false' # Suppress npm update messages

  # Step 2: Install apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: 'npm'
    args: ['install', '-g', 'apigeelint']

  # --- DIAGNOSTIC STEPS ---

  # Diagnostic Step D: Attempt to find apigeelint executable
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'which apigeelint || echo "apigeelint not found in PATH"'
    id: 'which-apigeelint'

  # Step 3: Run apigeelint
  - name: 'node'  # Use the same Node.js version
    entrypoint: '/usr/local/bin/apigeelint'  # Use the standard global install location
    args:
      - '-s'
      - '/home/andrew/apigee-proxies/apiproxy'
      - '-f'
      - 'table.js'
    env:
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'  # Explicitly set PATH including /usr/local/bin